[gcp_service_account]
type = "service_account"
project_id = "entering-abode-426300-h6"
private_key_id = "21e2fa59e9b7680ff706c7d6714742baff0c0bd6"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwQWFB4/Ro6v8I\nueLOkd9yff3tkBd+CT8DhnrnkQLtylAsZCmqzpGSgDYDp7fvWYbXtzopbuOJ/jRg\n... (continúa todo el contenido de la clave) ...\n-----END PRIVATE KEY-----\n"
client_email = "datosbarriles@centering-abode-426300-h6.iam.gserviceaccount.com"
client_id = "114278788179798339797"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/datosbarriles%40centering-abode-426300-h6.iam.gserviceaccount.com"
